### ISSUE TITLE
No record for sportssystems.com

### ISSUE THREAD

**Issue by bakerjalexander** [jsarenik/spf-tools#124]
Using latest files from Jan 18, ./despf.sh sportssystems.com gives nothing, but

dig TXT sportssystems.com +short gives
"GOOGLE-SITE-VERIFICATION=KA6GOR_NXZNHOXANLL7PQSDIPZVJ21ZOQQBWZOHVIKU"
"V=SPF1 include:_spf.google.com IP4:166.78.205.64 IP4:166.78.205.65 IP4:166.78.205.66 IP4:216.73.93.70/31 IP4:216.73.93.72/31 MX PTR A ~ALL"

Wondering if the presence of the MX, PTR and A records have anything to do with it and also if they're handled properly, i.e. are lookups done for those records or is it just the ip addresses and include statements that are processed? 

(I wouldn't bother with looking up PTR records myself, their use is strongly discouraged by RFC 7208 with SPF records)

**Comment by jsarenik** [comment]
Very good point. Currently `spf-tools` are matching strings case-sensitive, i.e. only lowercase.

The RFC says https://tools.ietf.org/html/rfc7208#section-12

> See [RFC5234] for ABNF notation.  Please note that as per this ABNF
> definition, literal text strings (those in quotes) are case-
> insensitive.  Hence, "mx" matches "mx", "MX", "mX", and "Mx".

**Comment by jsarenik** [comment]
@bakerjalexander please try the code from pull-request #125 and let me know if it helps.

**Comment by jsarenik** [comment]
@bakerjalexander - and this one, can it be closed now? Thanks.
