### ISSUE TITLE
Handle macros in spf entries

### ISSUE THREAD

**Issue by jcbf** [jsarenik/spf-tools#133]
Although  there isn't a wide spread usage , entries with macros shouldn't be processed.
For instance, gentoo.org has some.

> gentoo.org.		60	IN	TXT	"v=spf1 include:_netblocks.spf.gentoo.org a:mail.gentoo.org mx include:%{l}.%{o}.spf.gentoo.org ?all"

**Comment by jsarenik** [comment]
Nice find. I have never seen anything like this before. How do the macros work? I can't see them in the [SPF Record Syntax](http://www.openspf.org/SPF_Record_Syntax) document. Thanks!

**Comment by jcbf** [comment]
Usually it's used with exists mechanism although  I've observed , more recently used in include mechanism. In theory you can use in any record.
Basically you can create dynamic records using stuff like IP address, email address, helo name as placeholders.
 
More information in https://tools.ietf.org/html/rfc7208#section-7

**Comment by jsarenik** [comment]
@jcbf Thanks for the link. I will have a look at it.
