### ISSUE TITLE
allow the possibility to keep untouched includes in the first SPF

### ISSUE THREAD

**Issue by lacostej** [jsarenik/spf-tools#152]
In order to authorize us, one of our mailing service provider (MailXXmp) insists on having their `include` as part of our first SPF, and won't search for it in the included sub-sections. So we need to keep it first.

Since 19ed7d50ee7a3ec3d7ba162643c66adc214d57d9 the `simplify.sh` script arbitrarily keep includes at the end.

So I've disabled the use of `simplify.sh`. Not sure if it could be modified to have a different default order, or at least configured to do so.

**Comment by jcbf** [comment]
How are you using despf.sh ? do you use -s ?

**Comment by jcbf** [comment]
Well, if you use -s to skip include expansion, those domains are shown first.  Then when the output is passed to `simplify.sh` the output is done in the following order:

- ip4 records
- ip6 records
- all other records

So, it's expected the behaviour you mentioned. There is no configurable option but you can pipe the output to a sort command like `./despf.sh | ./normalize.sh | ./simplify.sh | sort | ./mkblocks.sh` to overcome this specific issue.

**Comment by lacostej** [comment]
Oh well. Didn't think of using sort... Thanks.

**Comment by lacostej** [comment]
And to answer your question, yes I was using `-s`, that's how the `include` end up not being transformed and left last in `simplify.sh`. I was wondering if there was any reason for letting those entries last, the commit I referred to in the description (19ed7d5) didn't give me much context for the change.

**Comment by jsarenik** [comment]
Hi @lacostej! Thanks for reporting this issue. What would you propose regarding the mentioned commit? Would you kindly describe a test that would check it works as you expect? Thanks.

**Comment by lacostej** [comment]
@jsarenik just  explaining why `simplify` orders the output in the current order (ipv4, ipv6, rest) would be sufficient to me. Is it arbitrary or was there a particular reason for this?

**Comment by jsarenik** [comment]
@lacostej as far as I know there is no particular reason for such ordering. As you properly noted, there's not much context in the mentioned commit either.

Ordering in general is very good (e.g. for filtering out repeated lines), but I'm not sure if there is any reason for this particular ordering.

@epf could you possibly have a look and add comment to your commit 19ed7d5?

**Comment by jsarenik** [comment]
@lacostej it this issue still alive?

**Comment by lacostej** [comment]
@jsarenik after looking at the commits made by @epf in Nov 2016 (https://github.com/jsarenik/spf-tools/commits/master?after=5e95140259a288dc9e73c82bc6862185f6de28c9+0, I think the change might have been 2 fold:
* add support for exists|ptr mechanisms
* add tests for those
* ensure some ordering to make testing easier

I am not sure at all there was a reason for ordering the elements more than that.

My particular issue is worked-around by using `sort` so I think we can close the issue.
