### ISSUE TITLE
Allow for cloudflare Automatic TTL

### ISSUE THREAD

**Issue by itxpress** [jsarenik/spf-tools#36]
The TTL is hardcoded at 1800 (which is certainly reasonable), but many Cloudflare users prefer the 'Automatic' setting so Cloudflare can choose the right value. According to the CF API docs, a TTL value of 1 will set it to 'Automatic'

""ttl"
TTL of record in seconds. 1 = Automatic, otherwise, value must in between 120 and 86400 seconds.

I guess you could do it in two ways - have some type of setting in the rc file indicating CloudFlare and then use 1 instead of 1800 or allow a TTL to be set in the RC file the same way.

Or have the cloudflare.sh script replace 1800 with 1, since it's use implies the availability of the Cloudflare Automatic TTL setting.

**Comment by jsarenik** [comment]
What version are you looking at? Because in my `cloudflare.sh` I see `TTL=1 # 1 = auto`.

**Comment by itxpress** [comment]
My bad - I completely missed that in the cloudflare script and kept seeing
1800 in all the other script output as I tested. Sorry about that.

On Sun, Nov 29, 2015 at 12:14 PM, Ján Sáreník <notifications@github.com>
wrote:

> What version are you looking at? Because in my cloudflare.sh I see TTL=1
> # 1 = auto.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsarenik/spf-tools/issues/36#issuecomment-160432697>.
>



-- 
Earned 'Best of 2015' award from Thumbtack.com!
Voted Best Computer Repair Business - 2014 & 2015!
 - Mebane Enterprise Reader's Choice Awards

IT Xpress - 1061 S Third St., Mebane, NC 27302
336-525-5005 - help@itxpress.biz - http://itxpress.biz
