### ISSUE TITLE
Update docs to help with jq dependency

### ISSUE THREAD

**Issue by itxpress** [jsarenik/spf-tools#38]
Was trying to setup spf-tools on a shared host setup that did not provide jq. I'm not a shell guru by any means, but was able to just download jq to my script directory and updated cloudflare.sh with 

alias jq="$PWD/jq"

to get things running. But you might want to update the readme section for cloudflare.sh to indicate the error:

./cloudflare.sh: line 14: type: jq: not found

Means you need to download jq locally and setup an alias to it (or there may be a more graceful way to do it - again not a shell guru by any stretch). Maybe a test within the local directory (or incldues) for a jq binary if one isn't found on the system.

**Comment by jsarenik** [comment]
Thanks for this report. I have added the dependencies list with links to upstream (GNU in case of basic utilities).

As for the extra tests or aliases - the scripts try to be as minimal as possible. There is no need to bloat simple scripts if the standard error messages are understandable. I hope it makes sense. Feel free to explain your point further.

Thanks!
