### ISSUE TITLE
Records  like a/24 or mx/24 ignores net mask

### ISSUE THREAD

**Issue by jcbf** [jsarenik/spf-tools#49]
records like a/24 and mx/24 get ignored.

Example:
```
dig +time=1 +short -t TXT mail.fcsny.com
"v=spf1 a/24 mx/24 -all"

./despf.sh mail.fcsny.com
ip4:199.231.151.110
```

**Comment by jsarenik** [comment]
I see it in SPF docs, but it's a strange thing as there is no distinction between IPv4 and IPv6 `a` in SPF. So if I set `a/24` and `AAAA` record for that domain is set, I get `fec0::7/24` :-) But I hope everyone who uses `a/netmask` or `mx/netmask` know what they are doing.

Thanks for the patch! Feel free to close now. There are also tests in #52
