### ISSUE TITLE
If primary DNS server fails, secondaries servers are not used

### ISSUE THREAD

**Issue by jcbf** [jsarenik/spf-tools#50]
``` ./despf.sh hotmail.com ```will trigger this query

```
 dig +time=2 +short -t TXT hotmail.com @ns4.msft.net. ns2.msft.net. ns1.msft.net. ns3.msft.net.
```

Ideas:

* Parse SOA record for primary and then query for NS records - badly configured "hidden primary" architectures 
* simple iterate by all NS servers and break on success.

**Comment by jsarenik** [comment]
Thanks for report! I think it's a very good idea to iterate and break. Working on it right now (on the drill branch).
