### ISSUE TITLE
isincidrange.sh /32 Check - Integer Expression Expected Warning

### ISSUE THREAD

**Issue by ninjada** [jsarenik/spf-tools#64]
Hello, been using spf-tools for a while to update our records. have recently added an include for aspmx.pardot.com and noted some errors/warnings.

If you run the command I use to generate my spf's, directly on aspmx.pardot.com it will reproduce the warnings eg.

./despf.sh aspmx.pardot.com | ./normalize.sh | ./simplify.sh | ./mkblocks.sh  | ./xsel.sh

will show following warnings, for every IP that goes through the 'isincidrange.sh' check when it gets checked against any IP listed as in a /32:

+ read cidr
+ mask=32
+ ciaddr=199.122.123.192
+ isincidrange.sh 74.86.241.250 199.122.123.192 32
/spf-tools/include/isincidrange.sh: line 55: test: 74.86.241.250: integer expression expected

From what I can tell it's due to the lookup finding an IP specified with the /32 range of which there is one in the above lookup:

ip4:13.111.0.1/24
ip4:13.111.1.0/24
ip4:136.147.135.1/24
ip4:136.147.176.1/24
ip4:136.147.182.1/24
ip4:174.36.84.12
ip4:174.36.84.14/31
ip4:174.36.84.245
ip4:174.36.84.32
ip4:198.245.81.1/24
ip4:199.122.123.188/30
** ip4:199.122.123.192/32
ip4:208.43.21.28
ip4:208.43.21.66
ip4:208.43.21.70
ip4:67.228.21.188
ip4:74.86.113.29
ip4:74.86.207.39
ip4:74.86.236.242
ip4:74.86.241.250

I guess it being superfluous/unnecessary to check against a /32, the isincidrange script doesn't handle this?

This seems to break the output and no SPF records will hit stdout when pressing enter. Could be wrong about the cause as incidrange.sh does seem to check against /32, but thats what I'm seeing with the above run.

**Comment by jsarenik** [comment]
Sorry for delayed reply. Let me have a look and I will be back with more info...

**Comment by jsarenik** [comment]
Thanks for this catch! I have a fix, just working on a test now. Thanks!!!

**Comment by jsarenik** [comment]
Sorry for auto-close - it was caused by my comment in the merge commit. Are you OK with this fix? Does it work for you now?

**Comment by ninjada** [comment]
@jsarenik Yep can confirm its working normally. 

Cheers man :+1:
