### ISSUE TITLE
Which OS has this been developed/tested on ?

### ISSUE THREAD

**Issue by regnauld** [jsarenik/spf-tools#72]
I've had some trouble getting any output from the tools on an older Ubuntu LTS and FreeBSD 10.1.
Obviously it's not your scope to support older/unsupported OSes, but it would be good to indicate somewhere on which platform spf-tools have been tested/developed, and which tools are expected to be available (dependencies) to the spf-tools suite.

The README.md references tac(1) - this isn't a standard command on BSDs, for instance.

**Comment by jsarenik** [comment]
Yes, `tac` is GNU Coreutils-specific as far as I know. But it is not required since a15746fae360bf7ea42439a45f9930378060a85b so thanks for noticing it in README - I have fixed it just now.

The shell code tries to by as POSIXish as I can, but it's true that I haven't tested it on *BSD or older Linux distros. I regularly run the tests on current rolling Arch Linux and the CI is done on Ubuntu (there are 4 different CI providers but I think they use almost the same Ubuntu version).

I will gladly have a look if you can provide more debugging output (i.e. running `sh -xe despf.sh` at least). Thanks!

**Comment by regnauld** [comment]
Ok, here comes the output below.

Also, on a system on which it works (14.04 LTS), I can see that /tmp/despf-loop-XXXXX contains (I modified the code not to cleanup for now):

random-non-match-tdaoeinthaonetuhanotehu
google.com
_spf.google.com
_netblocks.google.com
_netblocks2.google.com
_netblocks3.google.com

... whereas on the FreeBSD system, I see:

random-non-match-tdaoeinthaonetuhanotehu
google.com

... so looks like DNS lookups aren't being performed or parsed correctly.


Output:

root@mail:/usr/local/site/bin # sh -xe despf.sh google.com
+ type dig
+ type awk
+ type grep
+ type sed
+ type cut
+ a=/despf.sh
+ a=''
+ a=''
+ a=.
+ cd .
+ pwd
+ BINDIR=/usr/local/site/bin
+ . /usr/local/site/bin/include/global.inc.sh
+ SPFTRC=/root/.spf-toolsrc
+ . /usr/local/site/bin/include/despf.inc.sh
+ DNS_TIMEOUT=2
+ test -r /root/.spf-toolsrc
+ mktemp /tmp/despf-loop-XXXXXXX
+ loopfile=/tmp/despf-loop-uZfI4OQ
+ echo random-non-match-tdaoeinthaonetuhanotehu
+ trap 'cleanup /tmp/despf-loop-uZfI4OQ; exit 1;' INT QUIT
+ domain=google.com
+ despfit google.com /tmp/despf-loop-uZfI4OQ
+ host=google.com
+ myloop=/tmp/despf-loop-uZfI4OQ
+ export LC_ALL=C
+ export LANG=C
+ grep .
+ despf google.com /tmp/despf-loop-uZfI4OQ
+ host=google.com
+ myloop=/tmp/despf-loop-uZfI4OQ
+ echo google.com
+ grep -qxFf /tmp/despf-loop-uZfI4OQ
+ echo google.com
+ parsepf google.com
+ host=google.com
+ test -n ''
+ sed -n 's/nameserver \([\.:0-9a-f]*\)/\1/p' /etc/resolv.conf
+ sed s/redirect=/include:/
+ myns=213.186.33.99
+ mydig -t TXT google.com @213.186.33.99
+ sed 's/^"//;s/"$//;s/" "//'
+ grep -E '^v=spf1\s+'
+ myspf=''
+ set +e
+ echo
+ grep -Eo 'include:\S+'
+ dogetem=''
+ echo
+ grep -Eo -w '(mx|a)((\/|:)\S+)?'
+ dogetamx=''
+ echo
+ grep -Eo 'ip[46]:\S+'
+ set -e
+ sort -u /tmp/despf-loop-uZfI4OQ-out
+ cleanup /tmp/despf-loop-uZfI4OQ
+ myloop=/tmp/despf-loop-uZfI4OQ
+ test -n /tmp/despf-loop-uZfI4OQ
+ rm /tmp/despf-loop-uZfI4OQ /tmp/despf-loop-uZfI4OQ-out
+ exit 1

**Comment by jsarenik** [comment]
@regnauld Thanks. What happens if you do `dig -t TXT google.com @213.186.33.99` ?

**Comment by regnauld** [comment]
$ dig -t TXT google.com @213.186.33.99

; <<>> DiG 9.10.3-P4 <<>> -t TXT google.com @213.186.33.99
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31719
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.                    IN      TXT

;; ANSWER SECTION:
google.com.             1320    IN      TXT     "v=spf1 include:_spf.google.com ~all"

;; AUTHORITY SECTION:
google.com.             29671   IN      NS      ns4.google.com.
google.com.             29671   IN      NS      ns3.google.com.
google.com.             29671   IN      NS      ns1.google.com.
google.com.             29671   IN      NS      ns2.google.com.

;; ADDITIONAL SECTION:
ns1.google.com.         202565  IN      A       216.239.32.10
ns2.google.com.         202565  IN      A       216.239.34.10
ns3.google.com.         202565  IN      A       216.239.36.10
ns4.google.com.         202565  IN      A       216.239.38.10

;; Query time: 0 msec
;; SERVER: 213.186.33.99#53(213.186.33.99)
;; WHEN: Tue Apr 05 16:22:12 CEST 2016
;; MSG SIZE  rcvd: 223

**Comment by jsarenik** [comment]
@regnauld OK, and now `dig +short -t TXT google.com`

**Comment by extremeshok** [comment]
if the look up returns a blank, I have a fix for this and will do a pull request.

**Comment by regnauld** [comment]
Ján Sáreník (notifications) writes:
> @regnauld OK, and now `dig +short -t TXT google.com`

	"v=spf1 include:_spf.google.com ~all"

**Comment by jsarenik** [comment]
I am sorry for silence. At the moment I have to do something else. Let's get back to it soon! Feel free to ping me (comment on this issue) to raise visibility in case I do not get back to it. Thanks!

**Comment by jsarenik** [comment]
@regnauld Please try to fetch the latest sources, run `tests/test-shell.sh || DEBUG=1 tests/test-shell.sh` and send me the output please. Thanks!

**Comment by regnauld** [comment]
$ tests/test-shell.sh || DEBUG=1 tests/test-shell.sh
=================================
Using /bin/sh
Testing ./despf
=================================
Using /bin/sh
+ set
+ grep SH_VERSION=
+ true
+ find . -type d -mindepth 1 -maxdepth 1
+ echo Testing ./despf
Testing ./despf
+ /bin/sh ./despf/cmd

**Comment by jsarenik** [comment]
@regnauld please checkout the branch `jasan/bsd` and send me the output of following commands: `git rev-parse HEAD; tests/test-shell.sh || DEBUG=1 tests/test-shell.sh; echo $?`

My output on FreeBSD 10.3-RELEASE is following:

```
252b59e33c94da5b70de3ddc6aab8d27ff2a40c0
=================================
Using /bin/sh
Testing ./a24
.. ./a24 OK
Testing ./brokendns
DNS lookup error!
.. ./brokendns OK
Testing ./despf
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./despf OK
Testing ./fix_32
.. ./fix_32 OK
Testing ./mkblocks
.. ./mkblocks OK
Testing ./mx20
.. ./mx20 OK
Testing ./norm_ignore
.. ./norm_ignore OK
Testing ./normalize
.. ./normalize OK
Testing ./nospf
.. ./nospf OK
Testing ./redirect
Getting orig.spf-tools.ml
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./redirect OK
Testing ./simplify
.. ./simplify OK
Testing despf functions...
.. Testing mydig -t TXT spf-tools.ml ...
.... OK
.. Testing mydig -t NS spf-tools.ml | sort ...
.... OK
.. Testing findns one.spf-tools.ml ...
.... OK
.. Testing findns orig.non-existent.nonnon ...
.... OK
.. Testing cat /tmp/spf-test-unit-DqSRAxDyN | printip ...
.... OK
.. Testing cat /tmp/spf-test-unit-DqSRAxDyN | printip ...
.... OK
.. Testing dea both.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml 24 ...
.... OK
.. Testing demx mx.spf-tools.ml ...
.... OK
.. Testing demx mx.spf-tools.ml 24 ...
.... OK
.. Testing demx spf-tools.ml 24 ...
.... OK
.. Testing getamx both-spf.spf-tools.ml a:both.spf-tools.ml ...
.... OK
.. Testing parsepf spf-tools.ml ...
.... OK
.. Testing parsepf morens.spf-tools.ml ...
.... OK
.. Testing parsepf mail.spf-tools.ml ...
.... OK
.. Testing isincidrange.sh 74.86.241.250 199.122.123.192 32 ...
.... OK
.. Testing isincidrange.sh 192.168.5.1 192.168.0.0 16 ...
.... OK
.. Testing checkval4 a.1.1.2 ...
.... OK
.. Testing checkval4 290.1.1.0 ...
.... OK
.. Testing checkval4 123.197.5 ...
.... OK
.. Testing checkval4 192.168.0.1 ...
.... OK
.. Testing checkval4 192.168.0.1 24 ...
.... OK
.. Testing checkval4 192.168.0.1 32 ...
.... OK
.. Testing checkval4 192.168.0.1 33 ...
.... OK
.. Testing checkval6 aaa::aab::aac ...
.... OK
.. Testing checkval6 aaq::aab ...
.... OK
.. Testing checkval6 aaaaa::aab ...
.... OK
.. Testing checkval6 ::1 ...
.... OK
.. Testing checkval6 ::1 64 ...
.... OK
.. Testing checkval6 ::1 129 ...
.... OK
.. Testing canon6 1:1 ...
.... OK
.. Testing canon6 1:1:1:1:1:1:1:1:1 ...
.... OK
.. Testing canon6 ::1 ...
.... OK
.. Testing numlesseq 25 25 ...
.... OK
.. Testing numlesseq 26 25 ...
.... OK
Testing with -n
.. cloudflare.sh ... OK
.. compare.sh ... OK
.. despf.sh ... OK
.. genspfzone.sh ... OK
.. mkblocks.sh ... OK
.. mkzoneent.sh ... OK
.. normalize.sh ... OK
.. runspftools.sh ... OK
.. simplify.sh ... OK
.. xsel.sh ... OK
0
````

**Comment by jsarenik** [comment]
The only extra setup I did on the FreeBSD system was to install git and bind like this:

```
pkg install git
pkg install bind910-9.10.3P4
```

**Comment by regnauld** [comment]
Will try right away. Just FYI, this also fails on Ubuntu 10.04 (I know, not supported).

**Comment by jsarenik** [comment]
Try that also on Ubuntu 10.04 if you have it handy, please.

**Comment by jsarenik** [comment]
Looks good. I managed to run it the same on Ubuntu 10.04:

```
0a05fe3cf031e4fc32cd1aa624f151905243bc85
=================================
Using /bin/sh
Testing ./mkblocks
.. ./mkblocks OK
Testing ./brokendns
DNS lookup error!
.. ./brokendns OK
Testing ./norm_ignore
.. ./norm_ignore OK
Testing ./nospf
.. ./nospf OK
Testing ./fix_32
.. ./fix_32 OK
Testing ./mx20
.. ./mx20 OK
Testing ./a24
.. ./a24 OK
Testing ./simplify
.. ./simplify OK
Testing ./normalize
.. ./normalize OK
Testing ./despf
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./despf OK
Testing ./redirect
Getting orig.spf-tools.ml
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./redirect OK
Testing despf functions...
.. Testing mydig -t TXT spf-tools.ml ...
.... OK
.. Testing mydig -t NS spf-tools.ml | sort ...
.... OK
.. Testing findns one.spf-tools.ml ...
.... OK
.. Testing findns orig.non-existent.nonnon ...
.... OK
.. Testing cat /tmp/spf-test-unit-K2KLxgFAh | printip ...
.... OK
.. Testing cat /tmp/spf-test-unit-K2KLxgFAh | printip ...
.... OK
.. Testing dea both.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml 24 ...
.... OK
.. Testing demx mx.spf-tools.ml ...
.... OK
.. Testing demx mx.spf-tools.ml 24 ...
.... OK
.. Testing demx spf-tools.ml 24 ...
.... OK
.. Testing getamx both-spf.spf-tools.ml a:both.spf-tools.ml ...
.... OK
.. Testing parsepf spf-tools.ml ...
.... OK
.. Testing parsepf morens.spf-tools.ml ...
.... OK
.. Testing parsepf mail.spf-tools.ml ...
.... OK
.. Testing isincidrange.sh 74.86.241.250 199.122.123.192 32 ...
.... OK
.. Testing isincidrange.sh 192.168.5.1 192.168.0.0 16 ...
.... OK
.. Testing checkval4 a.1.1.2 ...
.... OK
.. Testing checkval4 290.1.1.0 ...
.... OK
.. Testing checkval4 123.197.5 ...
.... OK
.. Testing checkval4 192.168.0.1 ...
.... OK
.. Testing checkval4 192.168.0.1 24 ...
.... OK
.. Testing checkval4 192.168.0.1 32 ...
.... OK
.. Testing checkval4 192.168.0.1 33 ...
.... OK
.. Testing checkval6 aaa::aab::aac ...
.... OK
.. Testing checkval6 aaq::aab ...
.... OK
.. Testing checkval6 aaaaa::aab ...
.... OK
.. Testing checkval6 ::1 ...
.... OK
.. Testing checkval6 ::1 64 ...
.... OK
.. Testing checkval6 ::1 129 ...
.... OK
.. Testing canon6 1:1 ...
.... OK
.. Testing canon6 1:1:1:1:1:1:1:1:1 ...
.... OK
.. Testing canon6 ::1 ...
.... OK
.. Testing numlesseq 25 25 ...
.... OK
.. Testing numlesseq 26 25 ...
.... OK
Testing with -n
.. cloudflare.sh ... OK
.. compare.sh ... OK
.. despf.sh ... OK
.. genspfzone.sh ... OK
.. mkblocks.sh ... OK
.. mkzoneent.sh ... OK
.. normalize.sh ... OK
.. runspftools.sh ... OK
.. simplify.sh ... OK
.. xsel.sh ... OK
=================================
Using /bin/dash
Testing ./mkblocks
.. ./mkblocks OK
Testing ./brokendns
DNS lookup error!
.. ./brokendns OK
Testing ./norm_ignore
.. ./norm_ignore OK
Testing ./nospf
.. ./nospf OK
Testing ./fix_32
.. ./fix_32 OK
Testing ./mx20
.. ./mx20 OK
Testing ./a24
.. ./a24 OK
Testing ./simplify
.. ./simplify OK
Testing ./normalize
.. ./normalize OK
Testing ./despf
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./despf OK
Testing ./redirect
Getting orig.spf-tools.ml
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./redirect OK
Testing despf functions...
.. Testing mydig -t TXT spf-tools.ml ...
.... OK
.. Testing mydig -t NS spf-tools.ml | sort ...
.... OK
.. Testing findns one.spf-tools.ml ...
.... OK
.. Testing findns orig.non-existent.nonnon ...
.... OK
.. Testing cat /tmp/spf-test-unit-47fqazw6X | printip ...
.... OK
.. Testing cat /tmp/spf-test-unit-47fqazw6X | printip ...
.... OK
.. Testing dea both.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml 24 ...
.... OK
.. Testing demx mx.spf-tools.ml ...
.... OK
.. Testing demx mx.spf-tools.ml 24 ...
.... OK
.. Testing demx spf-tools.ml 24 ...
.... OK
.. Testing getamx both-spf.spf-tools.ml a:both.spf-tools.ml ...
.... OK
.. Testing parsepf spf-tools.ml ...
.... OK
.. Testing parsepf morens.spf-tools.ml ...
.... OK
.. Testing parsepf mail.spf-tools.ml ...
.... OK
.. Testing isincidrange.sh 74.86.241.250 199.122.123.192 32 ...
.... OK
.. Testing isincidrange.sh 192.168.5.1 192.168.0.0 16 ...
.... OK
.. Testing checkval4 a.1.1.2 ...
.... OK
.. Testing checkval4 290.1.1.0 ...
.... OK
.. Testing checkval4 123.197.5 ...
.... OK
.. Testing checkval4 192.168.0.1 ...
.... OK
.. Testing checkval4 192.168.0.1 24 ...
.... OK
.. Testing checkval4 192.168.0.1 32 ...
.... OK
.. Testing checkval4 192.168.0.1 33 ...
.... OK
.. Testing checkval6 aaa::aab::aac ...
.... OK
.. Testing checkval6 aaq::aab ...
.... OK
.. Testing checkval6 aaaaa::aab ...
.... OK
.. Testing checkval6 ::1 ...
.... OK
.. Testing checkval6 ::1 64 ...
.... OK
.. Testing checkval6 ::1 129 ...
.... OK
.. Testing canon6 1:1 ...
.... OK
.. Testing canon6 1:1:1:1:1:1:1:1:1 ...
.... OK
.. Testing canon6 ::1 ...
.... OK
.. Testing numlesseq 25 25 ...
.... OK
.. Testing numlesseq 26 25 ...
.... OK
Testing with -n
.. cloudflare.sh ... OK
.. compare.sh ... OK
.. despf.sh ... OK
.. genspfzone.sh ... OK
.. mkblocks.sh ... OK
.. mkzoneent.sh ... OK
.. normalize.sh ... OK
.. runspftools.sh ... OK
.. simplify.sh ... OK
.. xsel.sh ... OK
=================================
Using /bin/bash
BASH_VERSION='4.1.5(1)-release'
Testing ./mkblocks
.. ./mkblocks OK
Testing ./brokendns
DNS lookup error!
.. ./brokendns OK
Testing ./norm_ignore
.. ./norm_ignore OK
Testing ./nospf
.. ./nospf OK
Testing ./fix_32
.. ./fix_32 OK
Testing ./mx20
.. ./mx20 OK
Testing ./a24
.. ./a24 OK
Testing ./simplify
.. ./simplify OK
Testing ./normalize
.. ./normalize OK
Testing ./despf
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./despf OK
Testing ./redirect
Getting orig.spf-tools.ml
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./redirect OK
Testing despf functions...
.. Testing mydig -t TXT spf-tools.ml ...
.... OK
.. Testing mydig -t NS spf-tools.ml | sort ...
.... OK
.. Testing findns one.spf-tools.ml ...
.... OK
.. Testing findns orig.non-existent.nonnon ...
.... OK
.. Testing cat /tmp/spf-test-unit-F1BwTzUEl | printip ...
.... OK
.. Testing cat /tmp/spf-test-unit-F1BwTzUEl | printip ...
.... OK
.. Testing dea both.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml 24 ...
.... OK
.. Testing demx mx.spf-tools.ml ...
.... OK
.. Testing demx mx.spf-tools.ml 24 ...
.... OK
.. Testing demx spf-tools.ml 24 ...
.... OK
.. Testing getamx both-spf.spf-tools.ml a:both.spf-tools.ml ...
.... OK
.. Testing parsepf spf-tools.ml ...
.... OK
.. Testing parsepf morens.spf-tools.ml ...
.... OK
.. Testing parsepf mail.spf-tools.ml ...
.... OK
.. Testing isincidrange.sh 74.86.241.250 199.122.123.192 32 ...
.... OK
.. Testing isincidrange.sh 192.168.5.1 192.168.0.0 16 ...
.... OK
.. Testing checkval4 a.1.1.2 ...
.... OK
.. Testing checkval4 290.1.1.0 ...
.... OK
.. Testing checkval4 123.197.5 ...
.... OK
.. Testing checkval4 192.168.0.1 ...
.... OK
.. Testing checkval4 192.168.0.1 24 ...
.... OK
.. Testing checkval4 192.168.0.1 32 ...
.... OK
.. Testing checkval4 192.168.0.1 33 ...
.... OK
.. Testing checkval6 aaa::aab::aac ...
.... OK
.. Testing checkval6 aaq::aab ...
.... OK
.. Testing checkval6 aaaaa::aab ...
.... OK
.. Testing checkval6 ::1 ...
.... OK
.. Testing checkval6 ::1 64 ...
.... OK
.. Testing checkval6 ::1 129 ...
.... OK
.. Testing canon6 1:1 ...
.... OK
.. Testing canon6 1:1:1:1:1:1:1:1:1 ...
.... OK
.. Testing canon6 ::1 ...
.... OK
.. Testing numlesseq 25 25 ...
.... OK
.. Testing numlesseq 26 25 ...
.... OK
Testing with -n
.. cloudflare.sh ... OK
.. compare.sh ... OK
.. despf.sh ... OK
.. genspfzone.sh ... OK
.. mkblocks.sh ... OK
.. mkzoneent.sh ... OK
.. normalize.sh ... OK
.. runspftools.sh ... OK
.. simplify.sh ... OK
.. xsel.sh ... OK
0
```

**Comment by regnauld** [comment]
FreeBSD output first:

0a05fe3cf031e4fc32cd1aa624f151905243bc85
=================================
Using /bin/sh
Testing ./redirect
Getting orig.spf-tools.ml
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./redirect OK
Testing ./normalize
.. ./normalize OK
Testing ./a24
.. ./a24 OK
Testing ./despf
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./despf OK
Testing ./nospf
.. ./nospf OK
Testing ./mx20
.. ./mx20 OK
Testing ./mkblocks
.. ./mkblocks OK
Testing ./fix_32
.. ./fix_32 OK
Testing ./simplify
.. ./simplify OK
Testing ./norm_ignore
.. ./norm_ignore OK
Testing ./brokendns
DNS lookup error!
.. ./brokendns OK
Testing despf functions...
.. Testing mydig -t TXT spf-tools.ml ...
.... OK
.. Testing mydig -t NS spf-tools.ml | sort ...
.... OK
.. Testing findns one.spf-tools.ml ...
.... OK
.. Testing findns orig.non-existent.nonnon ...
.... OK
.. Testing cat /tmp/spf-test-unit-dUXVuFFCm | printip ...
.... OK
.. Testing cat /tmp/spf-test-unit-dUXVuFFCm | printip ...
.... OK
.. Testing dea both.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml 24 ...
.... OK
.. Testing demx mx.spf-tools.ml ...
.... OK
.. Testing demx mx.spf-tools.ml 24 ...
.... OK
.. Testing demx spf-tools.ml 24 ...
.... OK
.. Testing getamx both-spf.spf-tools.ml a:both.spf-tools.ml ...
.... OK
.. Testing parsepf spf-tools.ml ...
.... OK
.. Testing parsepf morens.spf-tools.ml ...
.... OK
.. Testing parsepf mail.spf-tools.ml ...
.... OK
.. Testing isincidrange.sh 74.86.241.250 199.122.123.192 32 ...
.... OK
.. Testing isincidrange.sh 192.168.5.1 192.168.0.0 16 ...
.... OK
.. Testing checkval4 a.1.1.2 ...
.... OK
.. Testing checkval4 290.1.1.0 ...
.... OK
.. Testing checkval4 123.197.5 ...
.... OK
.. Testing checkval4 192.168.0.1 ...
.... OK
.. Testing checkval4 192.168.0.1 24 ...
.... OK
.. Testing checkval4 192.168.0.1 32 ...
.... OK
.. Testing checkval4 192.168.0.1 33 ...
.... OK
.. Testing checkval6 aaa::aab::aac ...
.... OK
.. Testing checkval6 aaq::aab ...
.... OK
.. Testing checkval6 aaaaa::aab ...
.... OK
.. Testing checkval6 ::1 ...
.... OK
.. Testing checkval6 ::1 64 ...
.... OK
.. Testing checkval6 ::1 129 ...
.... OK
.. Testing canon6 1:1 ...
.... OK
.. Testing canon6 1:1:1:1:1:1:1:1:1 ...
.... OK
.. Testing canon6 ::1 ...
.... OK
.. Testing numlesseq 25 25 ...
.... OK
.. Testing numlesseq 26 25 ...
.... OK
Testing with -n
.. cloudflare.sh ... OK
.. compare.sh ... OK
.. despf.sh ... OK
.. genspfzone.sh ... OK
.. mkblocks.sh ... OK
.. mkzoneent.sh ... OK
.. normalize.sh ... OK
.. runspftools.sh ... OK
.. simplify.sh ... OK
.. xsel.sh ... OK
=================================
Using /usr/local/bin/bash
BASH_VERSION='4.3.42(1)-release'
Testing ./redirect
Getting orig.spf-tools.ml
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./redirect OK
Testing ./normalize
.. ./normalize OK
Testing ./a24
.. ./a24 OK
Testing ./despf
Getting both.spf-tools.ml
Getting mx20.spf-tools.ml
Getting a24.spf-tools.ml
.. ./despf OK
Testing ./nospf
.. ./nospf OK
Testing ./mx20
.. ./mx20 OK
Testing ./mkblocks
.. ./mkblocks OK
Testing ./fix_32
.. ./fix_32 OK
Testing ./simplify
.. ./simplify OK
Testing ./norm_ignore
.. ./norm_ignore OK
Testing ./brokendns
DNS lookup error!
.. ./brokendns OK
Testing despf functions...
.. Testing mydig -t TXT spf-tools.ml ...
.... OK
.. Testing mydig -t NS spf-tools.ml | sort ...
.... OK
.. Testing findns one.spf-tools.ml ...
.... OK
.. Testing findns orig.non-existent.nonnon ...
.... OK
.. Testing cat /tmp/spf-test-unit-NTSQ1cofY | printip ...
.... OK
.. Testing cat /tmp/spf-test-unit-NTSQ1cofY | printip ...
.... OK
.. Testing dea both.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml ...
.... OK
.. Testing dea cname.spf-tools.ml 24 ...
.... OK
.. Testing demx mx.spf-tools.ml ...
.... OK
.. Testing demx mx.spf-tools.ml 24 ...
.... OK
.. Testing demx spf-tools.ml 24 ...
.... OK
.. Testing getamx both-spf.spf-tools.ml a:both.spf-tools.ml ...
.... OK
.. Testing parsepf spf-tools.ml ...
.... OK
.. Testing parsepf morens.spf-tools.ml ...
.... OK
.. Testing parsepf mail.spf-tools.ml ...
.... OK
.. Testing isincidrange.sh 74.86.241.250 199.122.123.192 32 ...
.... OK
.. Testing isincidrange.sh 192.168.5.1 192.168.0.0 16 ...
.... OK
.. Testing checkval4 a.1.1.2 ...
.... OK
.. Testing checkval4 290.1.1.0 ...
.... OK
.. Testing checkval4 123.197.5 ...
.... OK
.. Testing checkval4 192.168.0.1 ...
.... OK
.. Testing checkval4 192.168.0.1 24 ...
.... OK
.. Testing checkval4 192.168.0.1 32 ...
.... OK
.. Testing checkval4 192.168.0.1 33 ...
.... OK
.. Testing checkval6 aaa::aab::aac ...
.... OK
.. Testing checkval6 aaq::aab ...
.... OK
.. Testing checkval6 aaaaa::aab ...
.... OK
.. Testing checkval6 ::1 ...
.... OK
.. Testing checkval6 ::1 64 ...
.... OK
.. Testing checkval6 ::1 129 ...
.... OK
.. Testing canon6 1:1 ...
.... OK
.. Testing canon6 1:1:1:1:1:1:1:1:1 ...
.... OK
.. Testing canon6 ::1 ...
.... OK
.. Testing numlesseq 25 25 ...
.... OK
.. Testing numlesseq 26 25 ...
.... OK
Testing with -n
.. cloudflare.sh ... OK
.. compare.sh ... OK
.. despf.sh ... OK
.. genspfzone.sh ... OK
.. mkblocks.sh ... OK
.. mkzoneent.sh ... OK
.. normalize.sh ... OK
.. runspftools.sh ... OK
.. simplify.sh ... OK
.. xsel.sh ... OK
0

**Comment by jsarenik** [comment]
The only extra packages I installed to a [precreated image](https://openvz.org/Download/template/precreated) of Ubuntu 10.04 (x86_64) were these:

```
git-core
dnsutils
```

**Comment by regnauld** [comment]
Also, note that the bind-tools should be enough (dig etc.), as opposed to the whole pkg.
That would be the equiv. of dnsutils for Ubuntu

**Comment by regnauld** [comment]
Ubuntu 10.04 attached - dnsutils wasn't installed, now it is.

[output.txt](https://github.com/jsarenik/spf-tools/files/219064/output.txt)

**Comment by jsarenik** [comment]
@regnauld Please run `rm -rfv /tmp/despf-loop*` on Ubuntu. The test tries to be nice and fails if there are leftover temp files (which are there since previous failed attempts). Thanks.

**Comment by jsarenik** [comment]
@regnauld BTW you can write in `code` when you use backticks. One backtick for `in text` and more than three before-and-after the block

```
for a block
of code/output
```

**Comment by jsarenik** [comment]
````
```
for a block
```
````

**Comment by jsarenik** [comment]
See https://guides.github.com/features/mastering-markdown/ for more.

**Comment by jsarenik** [comment]
Merging in and closing this issue. Thanks for reporting and testing @regnauld !!!
