### ISSUE TITLE
Make test scripts executable

### ISSUE THREAD

**Issue by jcbf** [jsarenik/spf-tools#84]
For simplicity test scripts should be executable.

```
-rw-r--r--  1 jcbf  staff   207 Apr 14 13:41 test-real.sh
-rwxr-xr-x  1 jcbf  staff   673 Apr 14 13:41 test-shell.sh
-rw-r--r--  1 jcbf  staff  1472 Apr 14 13:41 test-unit.sh
```

**Comment by jcbf** [comment]
Since there is no content change, I can't make the pull request :p

**Comment by jsarenik** [comment]
The reasoning behind that was that only `test-shell.sh` is meant to be run. Now all of them can be run separately.

**Comment by jsarenik** [comment]
@jcbf nice idea, it also made me streamline the scripts and rename the `test-real` to `test-subdirs`
