### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by jcbf** [jsarenik/spf-tools#86]
There are 232 commits to master since release 1.0. Looking at the closed issues I think is worth a new release , let's say v1.1.
What do you think ? 

Just as reference, this is a generated ChangeLog

# Change Log

## [Unreleased](https://github.com/jsarenik/spf-tools/tree/HEAD)

[Full Changelog](https://github.com/jsarenik/spf-tools/compare/v1.0...HEAD)

**Implemented enhancements:**

- Check for valid ip records [\#48](https://github.com/jsarenik/spf-tools/issues/48)
- Update docs to help with jq dependency [\#38](https://github.com/jsarenik/spf-tools/issues/38)
- despf.sh fails to follow "redirect" in SPF records [\#27](https://github.com/jsarenik/spf-tools/issues/27)

**Fixed bugs:**

- Truncated DNS results cause issues [\#53](https://github.com/jsarenik/spf-tools/issues/53)
- If primary DNS server fails, secondaries servers are not used [\#50](https://github.com/jsarenik/spf-tools/issues/50)
- Records  like a/24 or mx/24 ignores net mask [\#49](https://github.com/jsarenik/spf-tools/issues/49)
- Detect Too Many SPF records [\#37](https://github.com/jsarenik/spf-tools/issues/37)
- despf.sh fails silently [\#33](https://github.com/jsarenik/spf-tools/issues/33)
- despf.sh fails to retrieve IP addresses from some domains [\#29](https://github.com/jsarenik/spf-tools/issues/29)

**Closed issues:**

- Make test scripts executable [\#84](https://github.com/jsarenik/spf-tools/issues/84)
- Allowing for multiple MX records [\#70](https://github.com/jsarenik/spf-tools/issues/70)
- isincidrange.sh /32 Check - Integer Expression Expected Warning [\#64](https://github.com/jsarenik/spf-tools/issues/64)

**Merged pull requests:**

- Make test scripts executable [\#85](https://github.com/jsarenik/spf-tools/pull/85) ([jsarenik](https://github.com/jsarenik))
- Rearrange AUTHORS a bit [\#83](https://github.com/jsarenik/spf-tools/pull/83) ([jsarenik](https://github.com/jsarenik))
- Jasan/bsd [\#82](https://github.com/jsarenik/spf-tools/pull/82) ([jsarenik](https://github.com/jsarenik))
- Extend debugging even more [\#81](https://github.com/jsarenik/spf-tools/pull/81) ([jsarenik](https://github.com/jsarenik))
- tests: Extend DEBUG on error [\#80](https://github.com/jsarenik/spf-tools/pull/80) ([jsarenik](https://github.com/jsarenik))
- Implement address checking for both v4 and v6 [\#79](https://github.com/jsarenik/spf-tools/pull/79) ([jsarenik](https://github.com/jsarenik))
- Jasan/dash [\#78](https://github.com/jsarenik/spf-tools/pull/78) ([jsarenik](https://github.com/jsarenik))
- misc/ci: Simplify setup using statically linked bins [\#77](https://github.com/jsarenik/spf-tools/pull/77) ([jsarenik](https://github.com/jsarenik))
- Better utilization of first TXT RR [\#76](https://github.com/jsarenik/spf-tools/pull/76) ([TheNoButton](https://github.com/TheNoButton))
- AUTHORS: add @TheNoButton and @regnauld [\#75](https://github.com/jsarenik/spf-tools/pull/75) ([jsarenik](https://github.com/jsarenik))
- README: Do not mention unused tac [\#74](https://github.com/jsarenik/spf-tools/pull/74) ([jsarenik](https://github.com/jsarenik))
- Jasan/multiple mx [\#73](https://github.com/jsarenik/spf-tools/pull/73) ([jsarenik](https://github.com/jsarenik))
- Update README.md [\#71](https://github.com/jsarenik/spf-tools/pull/71) ([regnauld](https://github.com/regnauld))
- README: Point all badges to master branch [\#69](https://github.com/jsarenik/spf-tools/pull/69) ([jsarenik](https://github.com/jsarenik))
- Get rid of findns [\#68](https://github.com/jsarenik/spf-tools/pull/68) ([jsarenik](https://github.com/jsarenik))
- Fix TravisCI [\#67](https://github.com/jsarenik/spf-tools/pull/67) ([jsarenik](https://github.com/jsarenik))
- Jasan/cleanup [\#66](https://github.com/jsarenik/spf-tools/pull/66) ([jsarenik](https://github.com/jsarenik))
- isincidrange.sh: Fix /32 case and add tests [\#65](https://github.com/jsarenik/spf-tools/pull/65) ([jsarenik](https://github.com/jsarenik))
- CI sync with drill branch [\#63](https://github.com/jsarenik/spf-tools/pull/63) ([jsarenik](https://github.com/jsarenik))
- Apache2 License [\#62](https://github.com/jsarenik/spf-tools/pull/62) ([jsarenik](https://github.com/jsarenik))
- Add iteration for other NS servers [\#60](https://github.com/jsarenik/spf-tools/pull/60) ([jsarenik](https://github.com/jsarenik))
- normalize.sh: Add -i switch to ignore invalid [\#59](https://github.com/jsarenik/spf-tools/pull/59) ([jsarenik](https://github.com/jsarenik))
- Cleanup Changes: [\#58](https://github.com/jsarenik/spf-tools/pull/58) ([jsarenik](https://github.com/jsarenik))
- Backport some interesting changes from drill branch [\#57](https://github.com/jsarenik/spf-tools/pull/57) ([jsarenik](https://github.com/jsarenik))
- findns: Filter out comments on stdout [\#56](https://github.com/jsarenik/spf-tools/pull/56) ([jsarenik](https://github.com/jsarenik))
- Add a Gitter chat badge to README.md [\#55](https://github.com/jsarenik/spf-tools/pull/55) ([gitter-badger](https://github.com/gitter-badger))
- Add tests for \#51 [\#52](https://github.com/jsarenik/spf-tools/pull/52) ([jsarenik](https://github.com/jsarenik))
- Fix for /jsarenik/spf-tools/\#49 [\#51](https://github.com/jsarenik/spf-tools/pull/51) ([jcbf](https://github.com/jcbf))
- README: Replace banner tabs with spaces [\#47](https://github.com/jsarenik/spf-tools/pull/47) ([jsarenik](https://github.com/jsarenik))
- Jasan/normalize test [\#46](https://github.com/jsarenik/spf-tools/pull/46) ([jsarenik](https://github.com/jsarenik))
- Jasan/rebase with correct jcbf [\#45](https://github.com/jsarenik/spf-tools/pull/45) ([jsarenik](https://github.com/jsarenik))
- Add a fancy banner to README [\#44](https://github.com/jsarenik/spf-tools/pull/44) ([jsarenik](https://github.com/jsarenik))
- Fix unneeded prefix [\#43](https://github.com/jsarenik/spf-tools/pull/43) ([jsarenik](https://github.com/jsarenik))
- Write the error message on stderr [\#42](https://github.com/jsarenik/spf-tools/pull/42) ([jsarenik](https://github.com/jsarenik))
- Add dependencies of cloudflare.sh to README [\#41](https://github.com/jsarenik/spf-tools/pull/41) ([jsarenik](https://github.com/jsarenik))
- Add .gitignore [\#40](https://github.com/jsarenik/spf-tools/pull/40) ([jsarenik](https://github.com/jsarenik))
- Make DNS timeout configurable [\#39](https://github.com/jsarenik/spf-tools/pull/39) ([jsarenik](https://github.com/jsarenik))
- Return 1 on empty output [\#35](https://github.com/jsarenik/spf-tools/pull/35) ([jsarenik](https://github.com/jsarenik))
- Add support for redirect [\#34](https://github.com/jsarenik/spf-tools/pull/34) ([jsarenik](https://github.com/jsarenik))
- A script to normalize the network part of a CIDR [\#32](https://github.com/jsarenik/spf-tools/pull/32) ([jcbf](https://github.com/jcbf))
- Jasan/jcbf [\#31](https://github.com/jsarenik/spf-tools/pull/31) ([jsarenik](https://github.com/jsarenik))
- v=spf1 must have a space. Proper handling of a and mx modifier [\#30](https://github.com/jsarenik/spf-tools/pull/30) ([jcbf](https://github.com/jcbf))
- README: Add General Usage, fix rest [\#26](https://github.com/jsarenik/spf-tools/pull/26) ([jsarenik](https://github.com/jsarenik))
- Make README badges more readable in raw [\#25](https://github.com/jsarenik/spf-tools/pull/25) ([jsarenik](https://github.com/jsarenik))
- Jasan/semaphore ci [\#24](https://github.com/jsarenik/spf-tools/pull/24) ([jsarenik](https://github.com/jsarenik))
- Jasan/fix test on mac [\#23](https://github.com/jsarenik/spf-tools/pull/23) ([jsarenik](https://github.com/jsarenik))
- Jasan/more ci tweaks [\#22](https://github.com/jsarenik/spf-tools/pull/22) ([jsarenik](https://github.com/jsarenik))
- Jasan/codeship [\#21](https://github.com/jsarenik/spf-tools/pull/21) ([jsarenik](https://github.com/jsarenik))
- Jasan/domain env [\#20](https://github.com/jsarenik/spf-tools/pull/20) ([jsarenik](https://github.com/jsarenik))
- Add CircleCI badge to README.md [\#19](https://github.com/jsarenik/spf-tools/pull/19) ([jsarenik](https://github.com/jsarenik))
- Add circle.yml [\#18](https://github.com/jsarenik/spf-tools/pull/18) ([jsarenik](https://github.com/jsarenik))
- Big changes branch + POSIX tweaks from \#12 [\#17](https://github.com/jsarenik/spf-tools/pull/17) ([jsarenik](https://github.com/jsarenik))
- Multiple big changes [\#16](https://github.com/jsarenik/spf-tools/pull/16) ([jsarenik](https://github.com/jsarenik))
- Be less verbose if particular shell is not found [\#14](https://github.com/jsarenik/spf-tools/pull/14) ([jsarenik](https://github.com/jsarenik))
- Add tests for mkblocks and simplify [\#13](https://github.com/jsarenik/spf-tools/pull/13) ([jsarenik](https://github.com/jsarenik))
- Merging back [\#11](https://github.com/jsarenik/spf-tools/pull/11) ([jsarenik](https://github.com/jsarenik))
- Add runspftools.sh background script [\#10](https://github.com/jsarenik/spf-tools/pull/10) ([jsarenik](https://github.com/jsarenik))
- Add DNS lookup limit and packet size variable [\#9](https://github.com/jsarenik/spf-tools/pull/9) ([jsarenik](https://github.com/jsarenik))
- Add delim variable to mkblocks.sh [\#8](https://github.com/jsarenik/spf-tools/pull/8) ([jsarenik](https://github.com/jsarenik))
- Make the requirements checks quiet [\#7](https://github.com/jsarenik/spf-tools/pull/7) ([jsarenik](https://github.com/jsarenik))
- Add more obvious reasoning to README [\#6](https://github.com/jsarenik/spf-tools/pull/6) ([jsarenik](https://github.com/jsarenik))
## [v1.0](https://github.com/jsarenik/spf-tools/tree/v1.0) (2015-01-20)
**Merged pull requests:**

- Forget about ptr in SPF [\#5](https://github.com/jsarenik/spf-tools/pull/5) ([jsarenik](https://github.com/jsarenik))
- Get rid of tac and use sed instead [\#4](https://github.com/jsarenik/spf-tools/pull/4) ([jsarenik](https://github.com/jsarenik))
- Fix mktemp parameter to make it Mac-ompatible [\#3](https://github.com/jsarenik/spf-tools/pull/3) ([jsarenik](https://github.com/jsarenik))
- Make it Mac-friendly [\#2](https://github.com/jsarenik/spf-tools/pull/2) ([jsarenik](https://github.com/jsarenik))
- Make README more fancy [\#1](https://github.com/jsarenik/spf-tools/pull/1) ([jsarenik](https://github.com/jsarenik))

\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*

**Comment by jsarenik** [comment]
Nice Changelog!

**Comment by jsarenik** [comment]
See Happy Monday release. Thanks for the Changelog!!!

**Comment by jsarenik** [comment]
https://github.com/jsarenik/spf-tools/releases/tag/v1.1

**Comment by jcbf** [comment]
Good! Should I close it?

**Comment by jsarenik** [comment]
Yes please.

-- 
https://jasan.tk
